In [ ]:
pip install sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd
import re
import re as reg
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
data = pd.read_excel('ReviewTerbaru.xlsx',sheet_name= 'total')


In [ ]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

slangs={'yg':'yang', 'tdk':'tidak', 'pd':'pada', 'mlh':'malah',
'jgn':'jangan', 'jg':'juga', 'tp':'tapi', 'blkg': 'belakang',
'dr':'dari', 'klo':'kalau', 'lg':'lagi','sj':'saja','bwt':'buat','cm':'cuma','sya':'saya','kalo':'kalau',
'kl':'kalau','dg':'dengan','krn':'karena', 'ank':'anak', 'maen':'main','bgt':'banget', 'rp':'rupiah', 'sat' : 'saat', 'sprtinya':'sepertinya','mlm':'malam',
'lbh':'lebih', 'tuju': 'tujuan','mayan' : 'lumayan', 'sat':'saat', 'sgt':'sangat', 'pol' : 'sangat', 'dg':'dengan','sabi':'bisa', 'byk' : 'banyak', 'gw' : 'aku',
'bs':'bisa','oeang':'orang','utk':'untuk'}

hasil_prep = []
for kalimat in data['Review']:
  prep = re.sub(r'\W', ' ', str(kalimat))

  prep = prep.lower()

  prep = re.sub(r'\d+', ' ', prep)

  prep = re.sub(r'\s+[a-zA-Z]\s+', ' ', prep)

  pattern=reg.compile(r"(.)\1{1,}",reg.DOTALL)
  prep=pattern.sub(r"\1",prep)

  words = prep.split()
  rfrm=[slangs[word] if word in slangs else word for word in words]
  prep= " ".join(rfrm)

  factory = StopWordRemoverFactory()
  more_stopword =  ['tak', 'jd', 'per', 'nya','buat','and','nan','to','is','bri','banget','the','for','this'] 

  stopwords = factory.get_stop_words() + more_stopword
  temp = [t for t in re.findall(r'\b[a-z]+-?[a-z]+\b',prep) if t not in stopwords]
  prep = ' '.join(temp)

  stemmer = StemmerFactory().create_stemmer()
  prep = stemmer.stem(prep)
  
  prep = re.sub(r'\s+', ' ', prep, flags=re.I)

  hasil_prep.append(prep)

In [ ]:
hasil_prep

In [ ]:
pip install xlsxwriter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import xlsxwriter
workbook = xlsxwriter.Workbook('hasilpreprocessing.xlsx', {'nan_inf_to_errors': True})
worksheet=workbook.add_worksheet()
row=0
col=0
x=data
hasilakhir=list(zip(x.Nama,x.Waktu,x.Rating,x.Review,hasil_prep))
worksheet.write(row, col, "Nama")
worksheet.write(row, col+1, "Waktu")
worksheet.write(row, col+2, "Rating")
worksheet.write(row, col+3, "Review")
worksheet.write(row, col+4, "CleanReview")
row+=1

for a,b,c,d,e in (hasilakhir):
  worksheet.write(row, col, a)
  worksheet.write(row, col+1, b)
  worksheet.write(row, col+2, c)
  worksheet.write(row, col+3, d)
  worksheet.write(row, col+4, e)
  row+=1

workbook.close()

In [85]:
dataset = pd.read_excel('hasilpreprocessing.xlsx', sheet_name='Sheet1')
data = dataset['CleanReview']
data = data.dropna()
data = data.values.tolist()
data = [str(x) for x in data]
data[:50]

['tempat wisata sekaligus rumah makan daerah baturaden tepat deket telaga sunyi luas guys sini outbound tiket masuk kesana penting sen makan maupun minum xixixi harga makan minum lumayan mahal emang tempat wisata cocok deh kumpul keluarga hunting foto dong view tarik bagus deh akses jalan kesana lumayan gampang si jalan nanjak kelok suasana adem asri deh poko mah bikin nyaman hayuk pernah mampir wajib mampir baturaden adventure forest',
 'libur lebaran padat ramai cocok keluarga',
 'deket dgn telaga sunyi hutan pinus limpakuwus sktr km timur lokawisata baturaden tempat sejuk biasa banyak unjung wekend libur sante sini nikmat makan minum enak tdi coba teh manis paket mendoan kriuk isi',
 'baf alih fungsi jadi restoran tempat jadi tarik makan tawar harga cukup jangkau pandang hutan pinus kursi kayu outdor sangat pas rekreasi atau ada acara event milaniparty ada acara beauty gathering event tahun jafra cosmetic',
 'tempat santa sama keluarga jamin muas wahana main tantang uji nyali tempat

In [ ]:
#TF
from sklearn.feature_extraction.text import CountVectorizer

tf_vectorizer = CountVectorizer(max_df=1.0, min_df=1)
tf = tf_vectorizer.fit_transform(data)

tf_terms = tf_vectorizer.get_feature_names()
print(tf_vectorizer.get_feature_names())
matrix = tf.toarray()
print(matrix)

['abadi', 'abdi', 'abiez', 'abis', 'able', 'about', 'abseil', 'abseiling', 'ac', 'acara', 'acountant', 'action', 'activities', 'ad', 'ada', 'adan', 'adap', 'adapun', 'adem', 'adik', 'adipati', 'adl', 'adrenalin', 'adrenaline', 'aduh', 'advanture', 'adventur', 'adventure', 'adventurenya', 'adventurnya', 'advorable', 'aer', 'aernya', 'aesthetic', 'afar', 'afdol', 'afordable', 'after', 'again', 'agam', 'agama', 'agathis', 'agatis', 'agenda', 'agk', 'aglonema', 'ago', 'agust', 'agustus', 'ah', 'ain', 'air', 'airna', 'airny', 'airterjunya', 'aja', 'ajah', 'ajak', 'ajal', 'ajar', 'ajib', 'ak', 'akal', 'akan', 'akar', 'akeh', 'akhir', 'akibat', 'akrab', 'akses', 'aksesoris', 'aksesorisnya', 'aksi', 'akta', 'aktif', 'aktifita', 'aktifitas', 'aktivitas', 'aku', 'akur', 'akurat', 'al', 'ala', 'aladin', 'alah', 'alam', 'alamat', 'alami', 'alamiah', 'alamya', 'alangkah', 'alas', 'alat', 'alhamdulilah', 'alhmdlqh', 'ali', 'alias', 'alih', 'alir', 'aliranya', 'alm', 'along', 'also', 'alternatif', 'a

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
#LDA
from sklearn.decomposition import LatentDirichletAllocation as LDA
jumlah_topics = 10
lda = LDA(n_components = jumlah_topics,learning_method ='batch',random_state = 0).fit(tf)
lda

LatentDirichletAllocation(random_state=0)

In [ ]:
#Training
train_topics = lda.transform(tf)

print(train_topics.shape)
print(train_topics)

(2164, 10)
[[0.15818655 0.19026441 0.00144985 ... 0.0014499  0.00144963 0.00144983]
 [0.87141486 0.01428725 0.01428676 ... 0.01428729 0.01428574 0.01428671]
 [0.00294179 0.0029415  0.21325161 ... 0.35846972 0.00294198 0.00294148]
 ...
 [0.00312553 0.0031253  0.00312614 ... 0.00312534 0.0031252  0.37337447]
 [0.29771417 0.00370412 0.00370469 ... 0.00370424 0.06649755 0.00370454]
 [0.00526454 0.00526405 0.56878006 ... 0.00526345 0.0622542  0.23907842]]


In [ ]:
print(lda.components_)

[[0.10006787 0.1        0.1        ... 0.1        3.1        1.09996927]
 [0.1        0.1        0.1        ... 0.1        0.1        0.1       ]
 [0.10000282 0.1        0.1        ... 0.1        0.10009344 0.1       ]
 ...
 [0.1        0.1        0.1        ... 0.10001973 0.1        0.1       ]
 [0.10001992 0.1        0.1        ... 0.1        0.1        0.1       ]
 [1.09998395 0.1        0.1        ... 0.1        3.09989321 0.10001655]]


In [ ]:
top_words = 5
topic_words = {}
for topic,comp in enumerate(lda.components_):
    word_index = np.argsort(comp)[::-1][:top_words]
    topic_words[topic] = [tf_vectorizer.get_feature_names()[i] + ' '+str(comp[i])for i in word_index]
    

In [ ]:
for topic,words in topic_words.items():
    print(f'Topic:{topic}')
    print(' , '.join(words))


Topic:0
tempat 317.90849850961615 , keluarga 199.6136146669992 , cocok 141.54075014312815 , bagus 116.23089709435843 , sama 85.65878384761896
Topic:1
air 72.21397625116401 , adem 55.47082488197963 , tempat 52.094155495389785 , seger 48.98341783659082 , dingin 36.69789485699673
Topic:2
anak 110.26080084900602 , tempat 93.73167071387171 , enak 74.15879585822435 , bagus 59.14102070006851 , kalau 51.031208982398276
Topic:3
banyak 145.29414370736933 , tempat 124.59472804701706 , anak 118.67362129896058 , masuk 113.63765525066769 , tiket 107.46016649206412
Topic:4
baturaden 171.31214471886904 , telaga 164.83497568795215 , wisata 153.16388219455385 , sunyi 121.40971242818624 , air 118.28113294538363
Topic:5
museum 31.158073530332892 , bank 22.33272409974282 , you 17.31314049542919 , purwokerto 16.79771140021616 , of 14.204803135134819
Topic:6
sejarah 98.51617918769222 , bank 80.8672680759233 , indonesia 69.15929550330877 , uang 67.78205022608252 , museum 67.74074816188524
Topic:7
sejuk 170.68

Kesimpulan: <br>
setelah dilakukan topic modelling pada data review di atas. Dapat kita simpulkan bahwa yang menjadi topik teratas adalah [tempat,air,baturraden,sejarah,sejuk,dan anak]